package prasad.leetcode.p2336;

import org.junit.Assert;
import org.junit.Test;

public class SmallestNumberInInfiniteSetTest {

    @Test
    public void test01() {
        SmallestNumberInInfiniteSet inInfiniteSet = new SmallestNumberInInfiniteSet();
        inInfiniteSet.addBack(2);  // content after the call: []  1,2,3,...
        Assert.assertEquals(1, inInfiniteSet.popSmallest());  // content after the call: []  2,3,4,...
        Assert.assertEquals(2, inInfiniteSet.popSmallest());  // content after the call: []  3,4,5,...
        Assert.assertEquals(3, inInfiniteSet.popSmallest());  // content after the call: []  4,5,6,...
        inInfiniteSet.addBack(1);  // content after the call: [1]  4,5,6,...
        Assert.assertEquals(1, inInfiniteSet.popSmallest());  // content after the call: []  4,5,6,...
        Assert.assertEquals(4, inInfiniteSet.popSmallest());  // content after the call: []  5,6,7,...
        Assert.assertEquals(5, inInfiniteSet.popSmallest());  // content after the call: []  6,7,8,...
        inInfiniteSet.addBack(4);  // content after the call: [4]  6,7,8,...
        inInfiniteSet.addBack(5);  // content after the call: [4,5]  6,7,8,...
        Assert.assertEquals(4, inInfiniteSet.popSmallest());  // content after the call: [5]  6,7,8,...
        Assert.assertEquals(5, inInfiniteSet.popSmallest());  // content after the call: []  6,7,8,...
        Assert.assertEquals(6, inInfiniteSet.popSmallest());  // content after the call: []  7,8,9,...
        inInfiniteSet.addBack(3);  // content after the call: [3]  7,8,9,...
        inInfiniteSet.addBack(6);  // content after the call: [3,6]  7,8,9,...
        inInfiniteSet.addBack(4);  // content after the call: [3,4,6]  7,8,9,...
        Assert.assertEquals(3, inInfiniteSet.popSmallest());  // content after the call: [4,6]  7,8,9,...
        Assert.assertEquals(4, inInfiniteSet.popSmallest());  // content after the call: [6]  7,8,9,...
    }
}
